<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MSI" failures="0" tests="6" name="com.TestNGdemo.Test_Parameter" time="4.044" errors="1" timestamp="2022-10-06T12:30:09 IST" skipped="0">
  <testcase classname="com.TestNGdemo.Test_Parameter" name="m1" time="0.001"/>
  <system-out/>
  <testcase classname="com.TestNGdemo.Test_Parameter" name="m2" time="0.002"/>
  <system-out/>
  <testcase classname="com.TestNGdemo.Test_Parameter" name="m5" time="4.028">
    <error message="Method com.TestNGdemo.Test_Parameter.m5() didn&#039;t finish within the time-out 4000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.TestNGdemo.Test_Parameter.m5() didn't finish within the time-out 4000
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:367)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:603)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- m5 -->
  <system-out/>
  <testcase classname="com.TestNGdemo.Test_Parameter" name="m3" time="0.007"/>
  <system-out/>
  <testcase classname="com.TestNGdemo.Test_Parameter" name="m4" time="0.002"/>
  <system-out/>
  <testcase classname="com.TestNGdemo.Test_Parameter" name="m6" time="0.004"/>
  <system-out/>
</testsuite> <!-- com.TestNGdemo.Test_Parameter -->
